---
after_success:
    - 'docker build -t matusdubrava/multi-client ./client'
    - 'docker build -t matusdubrava/multi-server ./server'
    - 'docker build -t matusdubrava/multi-nginx ./nginx'
    - 'docker build -t matusdubrava/multi-worker ./worker'
    - 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin'
    - 'docker push matusdubrava/multi-client'
    - 'docker push matusdubrava/multi-server'
    - 'docker push matusdubrava/multi-nginx'
    - 'docker push matusdubrava/multi-worker'
before_install:
    - 'docker build -t matusdubrava/react-test -f ./client/Dockerfile.dev ./client'
script:
    - 'docker run matusdubrava/react-test npm run test -- --coverage'
services:
    - docker
sudo: required
deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-859119227216
    bucket_path: multi-docker
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
